//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Esecurity.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public int TestCategory { get; set; }
        public string TestResult { get; set; }
        public string CompanyId { get; set; }
        public System.DateTime TestDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
